-- Create the beer_drafts table
CREATE TABLE IF NOT EXISTS beer_drafts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image TEXT NOT NULL,
  brewery TEXT NOT NULL,
  name TEXT NOT NULL,
  style TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  price_glass NUMERIC NOT NULL DEFAULT 0,
  price_pint NUMERIC NOT NULL DEFAULT 0,
  alcohol NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add RLS policies (adjust based on your auth setup, assuming authenticated users can manage drafts)
ALTER TABLE beer_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON beer_drafts
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Enable insert for authenticated users" ON beer_drafts
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON beer_drafts
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable delete for authenticated users" ON beer_drafts
  FOR DELETE
  TO authenticated
  USING (true);

